<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Googlemap\Module'                        => __DIR__ . '/Module.php',
    'Googlemap\Controller\GooglemapController' => __DIR__ . '/src/Googlemap/Controller/GooglemapController.php',
    'GooglemapTest\Framework\TestCase'        => __DIR__ . '/tests/Googlemap/Framework/TestCase.php',
    'GooglemapTest\SampleTest'                => __DIR__ . '/tests/Googlemap/SampleTest.php',
);
